# Generated by Django 4.2.9 on 2024-02-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('news_date', models.DateField()),
                ('address', models.TextField()),
                ('url', models.TextField()),
                ('img', models.TextField()),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('hash_password', models.CharField(max_length=255)),
                ('test', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'myapp_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('feedback_date', models.DateField()),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.news')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'managed': True,
            },
        ),
    ]
